arcan-output: arcan_out
dataset_builder_path: dataset_builder
data_output_path: dataset_builder/data

#projects
projects:
  #- antlr4-hl-20-21
  #- antlr4-hl-22-23
  - antlr4-hl-23-24-25
  #- commons-lang-hl-20-21
  #- commons-lang-hl-22-23
  - commons-lang-hl-23-24-25
  #- db-jdo-hl-20-21
  #- db-jdo-hl-22-23
  - db-jdo-hl-23-24-25
  #- dubbo-hl-20-21
  #- dubbo-hl-22-23
  #- kafka-hl-20-21
  #- kafka-hl-22-23
  #- kafka-hl-24-25
  #- openjpa-hl-20-21
  #- openjpa-hl-22-23
  #- openjpa-hl-24-25
  #- opennlp-hl-20-21
  #- opennlp-hl-22-23
  - opennlp-hl-23-24-25
  #- ozone-hl-20-21
  #- ozone-hl-22-23
  #- ozone-hl-24-25

# Features da estrarre dai nodi (le metriche topologiche vengono aggiunte automaticamente)
node_features:
  - FanIn
  - FanOut
  - PageRank
  - LinesOfCode
  - NumberOfChildren
  - InstabilityMetric
  - AbstractnessMetric
  - TotalAmountOfChanges

# Features da estrarre dagli archi
edge_features:
  - Weight
  - SmellExtentByWeight
  - Inferred

# Features specifiche per gli smell (opzionale)
smell_features:
  - "smellType"
  - "Severity"
  - "Size"
  - "Strength"

# Configurazione per l'estrazione dei subgrafi
extraction:
  # Dimensione massima del grafo completo (nodi)
  max_graph_size: 10000

  # Dimensione minima del subgrafo estratto (nodi)
  min_subgraph_size: 3

  # Raggio per l'ego-graph (1 = 1-hop neighbors)
  radius: 1

  # Include campioni non-smelly per bilanciare il dataset
  include_non_smelly: true

  # Abilita processamento parallelo (può usare molta memoria)
  parallel_processing: false

  # Estrai anche le sequenze expert
  extract_sequences: true

# Filtri di qualità per i subgrafi
quality_filters:
  # Rimuovi nodi isolati dal subgrafo
  remove_isolated_nodes: true

  # Numero minimo di archi nel subgrafo
  min_edges: 1

# Configurazione per il bilanciamento del dataset
dataset_balance:
  # Rapporto target smelly/non-smelly (1.0 = bilanciato)
  target_ratio: 1.0

  # Strategia per il bilanciamento: "oversample", "undersample", "none"
  balance_strategy: "none"

  # Seed per riproducibilità
  random_seed: 42

# Configurazione per il logging e debugging
logging:
  # Livello di log: DEBUG, INFO, WARNING, ERROR
  level: "INFO"

  # Salva log dettagliati su file
  save_to_file: true

  # Directory per i log
  log_dir: "logs"

# Configurazione per ottimizzazioni performance
performance:
  # Usa cache per evitare riprocessing
  use_cache: true

  # Chunk size per processamento batch
  chunk_size: 100

  # Numero massimo di worker per parallelizzazione
  max_workers: 4

# Configurazione per validazione e testing
validation:
  # Esegui controlli di validazione
  enable_validation: true

  # Percentuale di campioni per validation set
  validation_split: 0.2

  # Cross-validation folds
  cv_folds: 5

# Configurazione output
output:
  # Formato di output: "pt" (PyTorch), "pickle", "json"
  format: "pt"

  # Comprimi i file di output
  compress: false

  # Prefisso per i nomi dei file
  file_prefix: ""

  # Includi timestamp nei nomi dei file
  include_timestamp: false

# Metadati aggiuntivi da salvare con ogni subgrafo
metadata:
  # Includi informazioni temporali
  include_temporal: true

  # Includi statistiche del grafo originale
  include_graph_stats: true

  # Includi hash del grafo per confronti
  include_graph_hash: true

  # Includi percorso del file sorgente
  include_source_path: true