name: HL_refactor_assistant_env
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.9.23
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pyg
  - absl-py=2.1.0
  - protobuf=3.20.3
  - scikit-learn=1.6.1
  - pandas=2.3.1
  - matplotlib=3.9.2
  - seaborn=0.13.2

  - pip
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.2.1
      - propcache==0.3.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - requests==2.32.4
      - sympy==1.14.0
      - tqdm==4.67.1
      - urllib3==2.5.0
      - yarl==1.20.1
      - zipp==3.23.0
