# Configuration for Clean Dataset Creation Pipeline

# Project paths
paths:
  arcan_output: "./arcan_out/intervalDays2"
  dataset_output: "./dataset/graph_features"

# Projects to process
projects:
  - antlr4-hl-20-21
  - antlr4-hl-22-23
  - antlr4-hl-24-25
  - antlr4-hl-23-24-25
  - commons-lang-hl-20-21
  - commons-lang-hl-22-23
  - commons-lang-hl-24-25
  - commons-lang-hl-23-24-25
  - db-jdo-hl-20-21
  - db-jdo-hl-22-23
  - db-jdo-hl-24-25
  - db-jdo-hl-23-24-25
  - dubbo-hl-20-21
  - dubbo-hl-22-23
  - kafka-hl-20-21
  - kafka-hl-22-23
  - kafka-hl-24-25
  - openjpa-hl-20-21
  - openjpa-hl-22-23
  - openjpa-hl-24-25
  - opennlp-hl-20-21
  - opennlp-hl-22-23
  - opennlp-hl-24-25
  - opennlp-hl-23-24-25
  - ozone-hl-20-21
  - ozone-hl-22-23
  - ozone-hl-24-25

# Extraction configuration
extraction:
  max_graph_size: 10000
  min_subgraph_size: 3
  max_subgraph_size: 200

  # Subgraph extraction
  radius: 1
  min_edges: 1
  remove_isolated_nodes: true

  # Sampling strategy
  include_non_smelly: true

  # Processing options
  parallel_processing: true

# Quality filters
quality_filters:
  remove_isolated_nodes: true
  min_edges: 1

# Feature extraction (fixed for hub detection)
node_features:
  - "fan_in"
  - "fan_out"
  - "degree_centrality"
  - "in_out_ratio"
  - "pagerank"
  - "betweenness_centrality"
  - "closeness_centrality"

# Edge features (currently not used - only connectivity maintained)
edge_features: []

# Smell detection features (currently not used)
smell_features: []

# Logging configuration
logging:
  level: "INFO"                  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

# Cache settings
cache:
  enable_smell_map_cache: true
  cache_directory: ".cache"      # Where to store cache files